global.consoleLog = ds_list_create()

print("Welcome to GEM"+string(GAME_VERSION_STRING)+"!")
print("If you need help on a specific command, just type 'help command'.")
print("You can get a more general help and a list of most commands by typing just 'help'.")
print("")
print("Report any bugs or requests on the GEM thread in the GG2 Forums. Thank you.")
print("-Orpheon and AJF")
print("")
print("----------------------------------------------------------------------------------")
print("")
